package edu.dod.core.domain;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import javax.persistence.*;

/**
 * DeliveryStatus Domain.
 * <p>This class has the attributes whether the demand request was real
 * and what is the delivery status for the demand</p>
 *
 * @author sky
 * @version 140506
 */
@Entity
@Table(name = "DeliveryStatus")
@NamedQueries({
        @NamedQuery(name = "DeliveryStatus.findById", query = "select distinct d from " +
                "DeliveryStatus d left join fetch d.demandHistory where d.demandID = :id")
})
public class DeliveryStatus {

    /**
     * Demand ID.
     * This ID is generated by a "foreign" key strategy.
     */
    @Id
    @GeneratedValue(generator = "gen")
    @GenericGenerator(name = "gen", strategy = "foreign", parameters = @Parameter(name = "property", value = "demandHistory"))
    @Column(name = "demand_id", unique = true, nullable = false)
    private int demandID;

    /**
     * Veracity of the delivery demand.
     * <p>
     * 0 = undefined, 1 = true & 2 = false.
     * </p>
     */
    @Column(name = "veracity")
    private int veracity;

    /**
     * Delivery status.
     * <p>
     * 0 = undefined, 1 = true & 2 = false.
     * </p>
     */
    @Column(name = "delivery_status")
    private int deliveryStatus;

    /**
     * DemandHistry mapped to this object.
     */
    @OneToOne
    @PrimaryKeyJoinColumn
    private DemandHistory demandHistory;

    /**
     * This empty constructor is required by hibernate binding mechanism.
     */
    public DeliveryStatus() {
    }

    /**
     * Constructor.
     *
     * @param demandID       a demand ID.
     * @param veracity       a veracity.
     * @param deliveryStatus a delivery status.
     */
    public DeliveryStatus(int demandID, int veracity, int deliveryStatus) {
        this.demandID = demandID;
        this.veracity = veracity;
        this.deliveryStatus = deliveryStatus;
    }

    public int getStatusID() {
        return demandID;
    }

    public void setStatusID(int statusID) {
        this.demandID = statusID;
    }

    public int getVeracity() {
        return veracity;
    }

    public void setVeracity(int veracity) {
        this.veracity = veracity;
    }

    public int getDeliveryStatus() {
        return deliveryStatus;
    }

    public void setDeliveryStatus(int deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    public DemandHistory getDemandHistory() {
        return demandHistory;
    }


    public void setDemandHistory(DemandHistory demandHistory) {
        this.demandHistory = demandHistory;
    }

}
